spring:
  profiles: prod
  flyway:
    baseline-on-migrate: true
    locations: classpath:db

  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/auth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:temppassword}
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: localhost
    port: 6379

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
management:
  health:
    db:
      enabled: false
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  config-location: classpath:/mybatis/config.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/eureka/
  instance:
    preferIpAddress: false
    hostname: ${AUTH_SERVICE_HOST:localhost}